### ISSUE TITLE
Let user be able to clear their database

### ISSUE THREAD

**Issue by Kurocifer** [xasterKies/pomanalyzer#1]
I think it will be nice if a user could be able to clear their database to start afresh totally clearing their work chart.

**Comment by xasterKies** [comment]
Hey @Kurocifer , 

Yes that will be very useful! Thank you for mentioning that out!

**Comment by xasterKies** [comment]
I just added a bash script that does the job. Will you like to add it to the README and create a pull request?

Here are the steps you should add before step where we are running the `go build` command:

1. Make the script executable by running `chmod +x clear_db.sh` if were running Linux or MacOS
2. Run the script with ./clear_db.sh

Do you think that is doable?

**Comment by Kurocifer** [comment]
Okay thanks. Just created a the pull request for this
